name: Build pdf file

on:
  push:
    branches:
      - ci
    paths:
      - "**/*.tex"

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: SamoKopecky/.github/.github/actions/publish-pdf-from-tex@main
        with:
          file_name: thesis
          github_token: ${{ secrets.GITHUB_TOKEN }}
