name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: SamoKopecky/.github/.github/actions/publish-pdf-from-tex@main
        with:
          file_name: thesis
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.repository }}
